version: '3'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    depends_on:
      - backend

  nginx:
    image: nginx
    container_name: webserver-node
    restart: always
    ports:
      - ${HOST_SERVER_PORT}:${CONT_SERVER_PORT}
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro

  db:
    image: postgres
    container_name: postgresdb-node
    restart: always
    volumes:
      - pgdb:/var/lib/postgresql/data

  redis-db:
    image: redis
    container_name: redisdb-node
  
  

volumes:
  pgdb: